# Generated by Django 5.2.7 on 2025-10-17 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_manager', '0002_booking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('performance', 'seat')},
        ),
    ]
